### ISSUE TITLE
为什么报错TypeError

### ISSUE THREAD

**Issue by will-bw** [HITgzx/Bing_Dwen_Dwen#1]
Traceback (most recent call last):
  File "D:\Code\bindundun2\Bing_Dwen_Dwen\Bing Dwen Dwen.py", line 138, in <module>
    pet = DesktopPet()
  File "D:\Code\bindundun2\Bing_Dwen_Dwen\Bing Dwen Dwen.py", line 41, in __init__
    self.randomPosition()
  File "D:\Code\bindundun2\Bing_Dwen_Dwen\Bing Dwen Dwen.py", line 126, in randomPosition
    self.move(width, height)
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'

**Comment by HITgzx** [comment]
这是数据类型的报错，move(self, int, int)要传入整数型，但是现在传了float，你可以试试使用下类型转换




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HITgzx/Bing_Dwen_Dwen"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 晚上10:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HITgzx/Bing_Dwen_Dwen] 为什么报错TypeError (Issue #1)





 
Traceback (most recent call last):
 File "D:\Code\bindundun2\Bing_Dwen_Dwen\Bing Dwen Dwen.py", line 138, in 
 pet = DesktopPet()
 File "D:\Code\bindundun2\Bing_Dwen_Dwen\Bing Dwen Dwen.py", line 41, in init
 self.randomPosition()
 File "D:\Code\bindundun2\Bing_Dwen_Dwen\Bing Dwen Dwen.py", line 126, in randomPosition
 self.move(width, height)
 TypeError: arguments did not match any overloaded call:
 move(self, QPoint): argument 1 has unexpected type 'float'
 move(self, int, int): argument 1 has unexpected type 'float'
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by will-bw** [comment]
> 

我换了个虚拟环境重新克隆没有报这个错误了
